{% set name = "qetpy" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61b373c2028ffbd378f024367dc7f54f17ce7a05f63d92be7ca0778602edb3b6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - iminuit >=2.0
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy
    - sympy
    - astropy
    - pandas
    - packaging

test:
  imports:
    - qetpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/spice-herald/QETpy
  summary: TES Detector Calibration and Analysis Python Tools
  license: GPL-2.0-or-later
  license_file: LICENSE
  description: |
    QETpy (Quasiparticle-trap-assisted Electrothermal-feedback Transition-edge sensors) provides
    a general set of tools for TES-based detector calibration and analysis. It contains submodules
    for noise modeling, IV analysis, complex impedance fitting, nonlinear optimum filter pulse fitting,
    and many other useful detector R&D analysis tools. This package is _NOT_ intended to contain any
    tools specific to a particular analysis. It is also meant to be DAQ independent, meaning it contains
    no IO functionality. It is assumed that the user is able to load their data as NumPy arrays separate
    from QETpy. 

extra:
  recipe-maintainers:
    - slwatkins
